**Варіант 3**

1 спосіб з використанням універсальних функцій бібліотеки NumPy.
номери завдань 1, 3, 6, 7, 8, 11, 16, 18, 19

In [1]:
import numpy as np

### Вправа 1.
Вводиться число $n$. Вивести масив розміру $n \times n$, в якому по діагоналі йдуть числа від $1$ до $n$, а інші числа дорівнюють $0$.

**In [2] task_1()**

 $5$  

**Out [2]** $$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 \\
0 & 2 & 0 & 0 & 0 \\
0 & 0 & 3 & 0 & 0 \\
0 & 0 & 0 & 4 & 0 \\
0 & 0 & 0 & 0 & 5
\end{bmatrix}
$$

In [58]:
n=int(input("Введіть число "))
a=np.arange(1,n+1,1)
f=np.diag(a)
f

Введіть число 5


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).

In [59]:
n = int(input("Введіть число n: "))
f_iter = [[(i + 1 if i == j else 0) for i in range(n)] for j in range(n)]
for row in f_iter:
    print(row)

Введіть число n: 5
[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]


Швидше виконана робота з пакетом NumPy

### Вправа 3.
Вводяться 4 числа $n, m, r, c$. Вивести масив розміру $n \times m$, в якому в кожному рядку з номером, кратним $r$, і в кожному стовпчику з номером, кратним $c$, стоять $0$, а інші елементи дорівнюють $1$.

**In [2] task_3()**
$6 \quad 7 \quad 2 \quad 3$

**Out [2]**
$$
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 1 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 1 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 1 & 0 & 1 & 1 & 0
\end{bmatrix}
$$

In [3]:
n=int(input("n="))
m=int(input("m="))
r=int(input("r="))
c=int(input("c="))
i,j=np.indices((n,m))
res=np.where((i%r==0)| (j%c==0), 0, 1)
res

n=4
m=5
r=6
c=4


array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0]])

b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).

In [34]:
n = int(input("n="))
m = int(input("m="))
r = int(input("r="))
c = int(input("c="))

res_list = [[(0 if (i % r == 0 or j % c == 0) else 1) for j in range(m)] for i in range(n)]

for row in res_list:
    print(row)

n=4
m=5
r=6
c=4
[0, 0, 0, 0, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]


Швидше виконана робота з пакетом NumPy

### Вправа 6.
З клавіатури вводиться масив. Замінити всі ненульові елементи на $-1$.

**In [2] task_6()** `3 4 0 9 7 0 6 0 4 0 3`

**Out [2]** $[-1 \quad -1 \quad 0 \quad -1 \quad -1 \quad 0 \quad -1 \quad 0 \quad -1 \quad 0 \quad -1]$


In [13]:

A2 = np.array(input("Введіть елементи масиву: ").split(), dtype=int)
res2= np.where(A2>0,-1,A2)
res2

Введіть елементи масиву: 4 5 6 0 0 0 


array([-1, -1, -1,  0,  0,  0])

b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).

In [35]:
A2 = [int(x) for x in input("Введіть елементи: ").split()]
res2 = []
for x in A2:
    if x > 0:
        res2.append(-1)
    else:
        res2.append(x)

print(res2)

Введіть елементи: 4 5 6 0 0 0 
[-1, -1, -1, 0, 0, 0]


### Вправа 7.
З клавіатури вводиться масив. Замінити всі нульові елементи на $-1$.

**In [2] task_7()**
`3 4 0 6 5 0 3 0 4`

**Out [2]**
$[3 \quad 4 \quad -1 \quad 6 \quad 5 \quad -1 \quad 3 \quad -1 \quad 4]$

In [62]:
res3=np.where(A2==0,-1,A2)
res3

array([4, 5, 6, 0, 0, 0])

b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).

In [61]:

A2 = [int(x) for x in input("Введіть елементи: ").split()]

res3 = []
for x in A2:
    if x == 0:
        res3.append(-1)
    else:
        res3.append(x)

print(res3)

Введіть елементи: 4 5 6 0 0 0 
[4, 5, 6, -1, -1, -1]


### Вправа 8.
З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

**In [2] task_8()**
`3 4 0 9 8 2 4 0 8 4 0`

**Out [2]**
Нулів: $3$  
Не нулів: $8$

In [66]:
A2= input("Введіть елементи масиву: ").split()
A2 = np.array(A2, dtype=int)
zero=np.count_nonzero(A2 == 0)
print("Нульові:",zero)
notzero=np.count_nonzero(A2 > 0)
print('НЕ нулі:',notzero)

Введіть елементи масиву: 3 4 0 9 8 2 4 0 8 4 0
Нульові: 3
НЕ нулі: 8


b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).

In [37]:

A2 = [int(x) for x in input("Введіть елементи: ").split()]

zero_count = 0
notzero_count = 0

for x in A2:
    if x == 0:
        zero_count += 1
    elif x > 0:
        notzero_count += 1

print("Нульові:", zero_count)
print("НЕ нулі:", notzero_count)

Введіть елементи: 3 4 0 9 8 2 4 0 8 4 0 
Нульові: 3
НЕ нулі: 8


### Вправа 11.
Створити масив одиниць розміром $n \times n$ та додати до нього «рамку», що утворюється з $0$.

**In [2] task_11()**
$4$

**Out [2]**
$$
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 1 & 1 & 1 & 0 \\
0 & 1 & 1 & 1 & 1 & 0 \\
0 & 1 & 1 & 1 & 1 & 0 \\
0 & 1 & 1 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0
\end{bmatrix}
$$

In [11]:
n=int(input("n="))
A3 = np.ones((n, n), dtype=int)
res = np.pad(A3, pad_width=1, mode='constant', constant_values=0)
res

n=4


array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).

In [38]:
n = int(input("n="))
size = n + 2
res = []
for i in range(size):
    row = [0] * size
    res.append(row)
for i in range(1, n + 1):
    for j in range(1, n + 1):
        res[i][j] = 1
for row in res:
    print(row)

n=4
[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]


### Вправа 16.
Заповнити вектор значеннями від $0$ до $n$. Всі значення, що більші за $n/4$ та менші за $3n/4$, замінити нулями.

**In [2] task_17()**
$10$

**Out [2]**
$[0 \quad 1 \quad 2 \quad 0 \quad 0 \quad 0 \quad 0 \quad 0 \quad 8 \quad 9 \quad 10]$

In [40]:
n=int(input("n="))
o=np.arange(0, n+1, 1)
res4 = np.where((o > n/4) & (o < 3*n/4), 0, o)
res4

n=10


array([ 0,  1,  2,  0,  0,  0,  0,  0,  8,  9, 10])

b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).


In [39]:
n = int(input("n="))
o = list(range(n + 1))

res4 = []
for x in o:
    if x > n/4 and x < 3*n/4:
        res4.append(0)
    else:
        res4.append(x)

print(res4)

n=10
[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]


### Вправа 18.
Згенерувати вектор з $n$ випадкових чисел в діапазоні від $0$ до $99$. Визначити кількість унікальних чисел в послідовності.

**In [2] task_19()** $30$

**Out [2]** В послідовності $[5, 77, 15, 21, 8, 44, 58, 77, 6, 49, 35, 35, 25, 3, 51, 65, 73, 81, 67, 78, 85, 68, 40, 77, 58, 1, 10, 9, 59, 13]$ — $26$ унікальних чисел

In [24]:
n=int(input("n="))
a=np.random.randint(0,100, n)
print(a)
m=np.unique(a)
count = len(m)
count

n=30
[88 14 68 19 25 99  5 56  6 69 66 26 58 84 81 10  9 73  6 90 66  4 96 74
 61 21 75 53 84 53]


26

b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).

In [41]:
import random

n = int(input("n="))
a = [random.randint(0, 99) for _ in range(n)]
print("Послідовність:", a)
unique_elements = []
for x in a:
    if x not in unique_elements:
        unique_elements.append(x)
count = len(unique_elements)
print("Кількість унікальних чисел:", count)

n=30
Послідовність: [73, 15, 79, 15, 30, 43, 21, 12, 63, 30, 5, 87, 63, 63, 89, 29, 63, 97, 33, 76, 55, 45, 59, 46, 30, 2, 16, 74, 25, 31]
Кількість унікальних чисел: 24


### Вправа 19.
$\text{Згенерувати вектор із } n \text{ елементів, що рівномірно}$
$\text{розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не}$
$\text{включені. Значення вивести до 3 знаків після коми.}$

**In [2] task_20()**
$10$

**Out [2]**
$[0.091 \quad 0.182 \quad 0.273 \quad 0.364 \quad 0.455 \quad 0.545 \quad 0.636 \quad 0.727 \quad 0.818 \quad 0.909]$

In [43]:
import numpy as np

n = int(input("n = "))
res = np.linspace(0, 1, n + 2)[1:-1]
print(np.round(res, 3))

n = 10
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).

In [44]:
n = int(input("n = "))
step = 1 / (n + 1)

res = []
for i in range(1, n + 1):

    value = round(i * step, 3)
    res.append(value)

print(res)

n = 10
[0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909]


NumPy швидший, бо він обробляє весь масив даних як один цілий блок, а не перевіряє кожне число окремо. Хоча на маленьких завданнях різниця непомітна, на великих даних NumPy економить купу часу.

### Завдання 2.
Розв’язати систему алгебраїчних рівнянь:
$$
\begin{cases}
x_1 + 2x_2 + 3x_3 + 4x_4 = 5 \\
2x_1 + x_2 + 2x_3 + 3x_4 = 1 \\
3x_1 + 2x_2 + x_3 + 2x_4 = 1 \\
4x_1 + 3x_2 + 2x_3 + x_4 = -5
\end{cases}
$$

за допомогою **формул Крамера** і виконати перевірку за допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції `numpy.linalg.solve()`.

Порівняти всі рішення за допомогою функції `numpy.allclose()`.

In [56]:
import numpy as np
A = np.array([
    [1, 2, 3, 4],
    [2, 1, 2, 3],
    [3, 2, 1, 2],
    [4, 3, 2, 1]
], dtype=float)

B = np.array([5, 1, 1, -5], dtype=float)

#Метод Крамера
def kramer_solve(A, B):
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0):
        return "Система не має однозначного розв'язку"

    x = []
    for i in range(len(B)):
        Ai = A.copy()
        Ai[:, i] = B
        x.append(np.linalg.det(Ai) / det_A)
    return np.array(x)

x_kramer = kramer_solve(A, B)

#b)Через обернену матрицю
A_inv = np.linalg.inv(A)
x_inv = A_inv @ B

#c)Через numpy.linalg.solve()
x_linalg = np.linalg.solve(A, B)

#a) Перевірка матричним множенням
check_mat = A @ x_linalg
is_equal = np.allclose(x_kramer, x_inv) and np.allclose(x_inv, x_linalg)

print("Розв'язок (Метод Крамера):", x_kramer)
print("Розв'язок (Обернена матриця):", x_inv)
print("Розв'язок (numpy.linalg.solve):", x_linalg)
print("Перевірка (A * x):", check_mat)
print("Чи всі рішення однакові:", is_equal)

Розв'язок (Метод Крамера): [-2.  2. -3.  3.]
Розв'язок (Обернена матриця): [-2.  2. -3.  3.]
Розв'язок (numpy.linalg.solve): [-2.  2. -3.  3.]
Перевірка (A * x): [ 5.  1.  1. -5.]
Чи всі рішення однакові: True


### Завдання 3.
Обчислити значення матричного виразу:
$$2(A - B)(A^2 + B)$$
де матриці $A$ та $B$ задані як:
$$
A = \begin{pmatrix} 5 & 1 & 7 \\ -10 & -2 & 1 \\ 0 & 1 & 2 \end{pmatrix}, \quad
B = \begin{pmatrix} 2 & 4 & 1 \\ 3 & 1 & 0 \\ 7 & 2 & 1 \end{pmatrix}
$$

**Виконати обчислення:**
а) з використанням універсальних функцій бібліотеки **NumPy**;
b) за допомогою **ітеративних конструкцій** (циклів, спискових включень тощо);
с) порівняти час виконання та зробити висновки.

In [57]:

import time
A = np.array([[5, 1, 7], [-10, -2, 1], [0, 1, 2]])
B = np.array([[2, 4, 1], [3, 1, 0], [7, 2, 1]])

#а) з використанням універсальних функцій бібліотеки NumPy
start_np = time.perf_counter()

res_np = 2 * (A - B) @ (A @ A + B)

end_np = time.perf_counter()
t_np = end_np - start_np

print("Результат NumPy:")
print(res_np)

#b)за допомогою ітеративних конструкцій (циклів)
start_iter = time.perf_counter()

A_sq = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(3):
    for j in range(3):
        for k in range(3):
            A_sq[i][j] += A[i][k] * A[k][j]

diff = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
summ = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(3):
    for j in range(3):
        diff[i][j] = A[i][j] - B[i][j]
        summ[i][j] = A_sq[i][j] + B[i][j]

temp_res = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(3):
    for j in range(3):
        for k in range(3):
            temp_res[i][j] += diff[i][k] * summ[k][j]

res_iter = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(3):
    for j in range(3):
        res_iter[i][j] = (2 * temp_res[i][j]).item()

end_iter = time.perf_counter()
t_iter = end_iter - start_iter

print("\nРезультат через цикли:")
for row in res_iter:
    print(row)


print(f"Час виконання NumPy: {t_np:.10f} сек.")
print(f"Час виконання циклів: {t_iter:.10f} сек.")
print(f"Різниця: у {round(t_iter/t_np, 1)} разів")
print("Результати ідентичні:", np.allclose(res_np, res_iter))

Результат NumPy:
[[ 228  132  798]
 [-286 -336 -894]
 [-190 -184 -562]]

Результат через цикли:
[228, 132, 798]
[-286, -336, -894]
[-190, -184, -562]
Час виконання NumPy: 0.0001512010 сек.
Час виконання циклів: 0.0007332900 сек.
Різниця: у 4.8 разів
Результати ідентичні: True
